### ISSUE TITLE
Sound mode missing?

### ISSUE THREAD

**Issue by spacecakes** [bang-olufsen/bang_olufsen-hacs#22]
Just updated to latest v2.x which went smoothly, but discovered that the sound mode entity is no longer available for my Beosound Theatre. Has that been removed or is this a bug? 

_Sidenote: Is there a list of differences somewhere between this integration and newly added official one?_

**Comment by mj23000** [comment]
The sound mode entity has been removed since the functionality should have been a part of the media_player entity from the beginning (Which it is now). You can control sound modes using the `media_player.select_sound_mode` action (or from the UI) and get sound modes from the `sound_mode_list` property.

There is currently no list of differences between the official and the HACS version, but that would be pretty useful, so I'll try to get that done.

**Comment by spacecakes** [comment]
I've been looking for it, but my Theatre doesn't expose a way to change sound modes. Only listening positions. 🤔

**Comment by cklit** [comment]
You dont have the selector on the more-info card (frontend)?

![Screenshot 2024-08-27 at 15 52 47](https://github.com/user-attachments/assets/a87d2e1a-c1b0-4673-aa8c-c440e71204a4)
